INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (1, 1, 'año', 'AH-nyoh', 'year', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (2, 1, 'día', 'DEE-ah', 'day', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (3, 1, 'casa', 'KAH-sah', 'house', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (4, 1, 'hombre', 'OHM-breh', 'man', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (5, 1, 'mujer', 'moo-HEHR', 'woman', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (6, 1, 'vida', 'BEE-dah', 'life', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (7, 1, 'mano', 'MAH-noh', 'hand', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (8, 1, 'ojo', 'OH-hoh', 'eye', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (9, 1, 'parte', 'PAR-teh', 'part', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (10, 1, 'tiempo', 'TYEM-poh', 'time', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (11, 1, 'vez', 'behth', 'time (occurrence)', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (12, 1, 'cosa', 'KOH-sah', 'thing', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (13, 1, 'ser', 'sehr', 'to be', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (14, 1, 'estar', 'ehs-TAR', 'to be (state)', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (15, 1, 'tener', 'teh-NEHR', 'to have', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (16, 1, 'hacer', 'ah-THEHR', 'to do', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (17, 1, 'decir', 'deh-THEER', 'to say', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (18, 1, 'ir', 'eer', 'to go', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (19, 1, 'ver', 'behr', 'to see', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (20, 1, 'dar', 'dar', 'to give', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (21, 1, 'saber', 'sah-BEHR', 'to know', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (22, 1, 'querer', 'keh-REHR', 'to want', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (23, 1, 'poder', 'poh-DEHR', 'to be able', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (24, 1, 'poner', 'poh-NEHR', 'to put', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (25, 1, 'venir', 'beh-NEER', 'to come', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (26, 1, 'de', 'deh', 'of', 'preposition', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (27, 1, 'la', 'lah', 'the (fem)', 'determiner', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (28, 1, 'que', 'keh', 'that', 'conjunction', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (29, 1, 'el', 'ehl', 'the (masc)', 'determiner', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (30, 1, 'en', 'ehn', 'in', 'preposition', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (31, 1, 'y', 'ee', 'and', 'conjunction', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (32, 1, 'a', 'ah', 'to', 'preposition', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (33, 1, 'los', 'lohs', 'the (m.pl)', 'determiner', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (34, 1, 'se', 'seh', 'oneself', 'pronoun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (35, 1, 'no', 'noh', 'no', 'adverb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (36, 1, 'un', 'oon', 'a (masc)', 'determiner', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (37, 1, 'por', 'por', 'for/by', 'preposition', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (38, 1, 'con', 'kohn', 'with', 'preposition', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (39, 1, 'una', 'OO-nah', 'a (fem)', 'determiner', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (40, 1, 'su', 'soo', 'his/her', 'determiner', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (41, 1, 'para', 'PAH-rah', 'for', 'preposition', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (42, 1, 'las', 'lahs', 'the (f.pl)', 'determiner', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (43, 1, 'lo', 'loh', 'it', 'pronoun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (44, 1, 'como', 'KOH-moh', 'as/like', 'conjunction', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (45, 1, 'más', 'mahs', 'more', 'adverb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (46, 1, 'pero', 'PEH-roh', 'but', 'conjunction', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (47, 1, 'le', 'leh', 'to him/her', 'pronoun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (48, 1, 'ya', 'yah', 'already', 'adverb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (49, 1, 'o', 'oh', 'or', 'conjunction', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (50, 1, 'este', 'EHS-teh', 'this', 'determiner', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (51, 2, 'agua', 'AH-gwah', 'water', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (52, 2, 'padre', 'PAH-dreh', 'father', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (53, 2, 'madre', 'MAH-dreh', 'mother', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (54, 2, 'hijo', 'EE-hoh', 'son', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (55, 2, 'niño', 'NEE-nyoh', 'child', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (56, 2, 'amigo', 'ah-MEE-goh', 'friend', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (57, 2, 'país', 'pah-EES', 'country', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (58, 2, 'mundo', 'MOON-doh', 'world', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (59, 2, 'ciudad', 'thyoo-DAHTH', 'city', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (60, 2, 'calle', 'KAH-yeh', 'street', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (61, 2, 'puerta', 'PWEHR-tah', 'door', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (62, 2, 'coche', 'KOH-cheh', 'car', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (63, 2, 'libro', 'LEE-broh', 'book', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (64, 2, 'mesa', 'MEH-sah', 'table', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (65, 2, 'cara', 'KAH-rah', 'face', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (66, 2, 'cabeza', 'kah-BEH-thah', 'head', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (67, 2, 'pie', 'pyeh', 'foot', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (68, 2, 'noche', 'NOH-cheh', 'night', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (69, 2, 'mañana', 'mah-NYAH-nah', 'morning', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (70, 2, 'trabajo', 'trah-BAH-hoh', 'work', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (71, 2, 'nombre', 'NOHM-breh', 'name', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (72, 2, 'gente', 'HEHN-teh', 'people', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (73, 2, 'hablar', 'ah-BLAR', 'to speak', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (74, 2, 'llevar', 'yeh-BAR', 'to carry', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (75, 2, 'pasar', 'pah-SAR', 'to pass', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (76, 2, 'dejar', 'deh-HAR', 'to leave (let)', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (77, 2, 'seguir', 'seh-GEER', 'to follow', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (78, 2, 'encontrar', 'ehn-kohn-TRAR', 'to find', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (79, 2, 'llamar', 'yah-MAR', 'to call', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (80, 2, 'creer', 'kreh-EHR', 'to believe', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (81, 2, 'pensar', 'pehn-SAR', 'to think', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (82, 2, 'salir', 'sah-LEER', 'to leave (exit)', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (83, 2, 'volver', 'bohl-BEHR', 'to return', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (84, 2, 'tomar', 'toh-MAR', 'to take', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (85, 2, 'conocer', 'koh-noh-THEHR', 'to know (person)', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (86, 2, 'vivir', 'bee-BEER', 'to live', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (87, 2, 'sentir', 'sehn-TEER', 'to feel', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (88, 2, 'mirar', 'mee-RAR', 'to look', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (89, 2, 'contar', 'kohn-TAR', 'to count/tell', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (90, 2, 'empezar', 'ehm-peh-THAR', 'to begin', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (91, 2, 'esperar', 'ehs-peh-RAR', 'to wait/hope', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (92, 2, 'buscar', 'boos-KAR', 'to search', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (93, 2, 'entrar', 'ehn-TRAR', 'to enter', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (94, 2, 'trabajar', 'trah-bah-HAR', 'to work', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (95, 2, 'escribir', 'ehs-kree-BEER', 'to write', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (96, 2, 'todo', 'TOH-doh', 'all', 'determiner', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (97, 2, 'sin', 'seen', 'without', 'preposition', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (98, 2, 'sobre', 'SOH-breh', 'on/about', 'preposition', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (99, 2, 'también', 'tahm-BYEHN', 'also', 'adverb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (100, 2, 'hasta', 'AHS-tah', 'until', 'preposition', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (101, 3, 'dios', 'dyohs', 'god', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (102, 3, 'rey', 'rray', 'king', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (103, 3, 'señor', 'seh-NYOR', 'sir/Mr.', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (104, 3, 'grupo', 'GROO-poh', 'group', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (105, 3, 'guerra', 'GEH-rrah', 'war', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (106, 3, 'historia', 'ees-TOH-ryah', 'history', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (107, 3, 'luz', 'looth', 'light', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (108, 3, 'fuego', 'FWEH-goh', 'fire', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (109, 3, 'aire', 'AY-reh', 'air', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (110, 3, 'tierra', 'TYEH-rrah', 'earth/land', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (111, 3, 'cielo', 'THYEH-loh', 'sky', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (112, 3, 'sol', 'sohl', 'sun', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (113, 3, 'luna', 'LOO-nah', 'moon', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (114, 3, 'mar', 'mar', 'sea', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (115, 3, 'río', 'RREE-oh', 'river', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (116, 3, 'flor', 'flor', 'flower', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (117, 3, 'árbol', 'AR-bohl', 'tree', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (118, 3, 'pan', 'pahn', 'bread', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (119, 3, 'vino', 'BEE-noh', 'wine', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (120, 3, 'comida', 'koh-MEE-dah', 'food', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (121, 3, 'voz', 'bohth', 'voice', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (122, 3, 'palabra', 'pah-LAH-brah', 'word', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (123, 3, 'corazón', 'koh-rah-THOHN', 'heart', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (124, 3, 'cuerpo', 'KWEHR-poh', 'body', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (125, 3, 'brazo', 'BRAH-thoh', 'arm', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (126, 3, 'boca', 'BOH-kah', 'mouth', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (127, 3, 'alma', 'AHL-mah', 'soul', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (128, 3, 'forma', 'FOR-mah', 'form', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (129, 3, 'razón', 'rrah-THOHN', 'reason', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (130, 3, 'idea', 'ee-DEH-ah', 'idea', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (131, 3, 'oír', 'oh-EER', 'to hear', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (132, 3, 'leer', 'leh-EHR', 'to read', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (133, 3, 'comer', 'koh-MEHR', 'to eat', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (134, 3, 'beber', 'beh-BEHR', 'to drink', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (135, 3, 'dormir', 'dor-MEER', 'to sleep', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (136, 3, 'correr', 'koh-RREHR', 'to run', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (137, 3, 'abrir', 'ah-BREER', 'to open', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (138, 3, 'cerrar', 'theh-RRAR', 'to close', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (139, 3, 'comprar', 'kohm-PRAR', 'to buy', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (140, 3, 'pagar', 'pah-GAR', 'to pay', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (141, 3, 'morir', 'moh-REER', 'to die', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (142, 3, 'bueno', 'BWEH-noh', 'good', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (143, 3, 'grande', 'GRAHN-deh', 'big', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (144, 3, 'pequeño', 'peh-KEH-nyoh', 'small', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (145, 3, 'nuevo', 'NWEH-boh', 'new', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (146, 3, 'viejo', 'BYEH-hoh', 'old', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (147, 3, 'muy', 'mwee', 'very', 'adverb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (148, 3, 'bien', 'byehn', 'well', 'adverb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (149, 3, 'entre', 'EHN-treh', 'between', 'preposition', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (150, 3, 'hay', 'ay', 'there is', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (151, 4, 'hermano', 'ehr-MAH-noh', 'brother', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (152, 4, 'hermana', 'ehr-MAH-nah', 'sister', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (153, 4, 'hija', 'EE-hah', 'daughter', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (154, 4, 'abuelo', 'ah-BWEH-loh', 'grandfather', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (155, 4, 'abuela', 'ah-BWEH-lah', 'grandmother', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (156, 4, 'familia', 'fah-MEE-lyah', 'family', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (157, 4, 'esposa', 'ehs-POH-sah', 'wife', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (158, 4, 'marido', 'mah-REE-doh', 'husband', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (159, 4, 'perro', 'PEH-rroh', 'dog', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (160, 4, 'gato', 'GAH-toh', 'cat', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (161, 4, 'caballo', 'kah-BAH-yoh', 'horse', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (162, 4, 'pájaro', 'PAH-hah-roh', 'bird', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (163, 4, 'pez', 'pehth', 'fish', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (164, 4, 'animal', 'ah-nee-MAHL', 'animal', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (165, 4, 'escuela', 'ehs-KWEH-lah', 'school', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (166, 4, 'iglesia', 'ee-GLEH-syah', 'church', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (167, 4, 'hospital', 'ohs-pee-TAHL', 'hospital', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (168, 4, 'hotel', 'oh-TEHL', 'hotel', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (169, 4, 'tienda', 'TYEHN-dah', 'shop', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (170, 4, 'plaza', 'PLAH-thah', 'square', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (171, 4, 'parque', 'PAR-keh', 'park', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (172, 4, 'montaña', 'mohn-TAH-nyah', 'mountain', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (173, 4, 'campo', 'KAHM-poh', 'field', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (174, 4, 'camino', 'kah-MEE-noh', 'road', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (175, 4, 'puente', 'PWEHN-teh', 'bridge', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (176, 4, 'ventana', 'behn-TAH-nah', 'window', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (177, 4, 'pared', 'pah-REHTH', 'wall', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (178, 4, 'suelo', 'SWEH-loh', 'floor', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (179, 4, 'silla', 'SEE-yah', 'chair', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (180, 4, 'cama', 'KAH-mah', 'bed', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (181, 4, 'ropa', 'RROH-pah', 'clothes', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (182, 4, 'zapato', 'thah-PAH-toh', 'shoe', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (183, 4, 'camisa', 'kah-MEE-sah', 'shirt', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (184, 4, 'dinero', 'dee-NEH-roh', 'money', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (185, 4, 'hora', 'OH-rah', 'hour', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (186, 4, 'minuto', 'mee-NOO-toh', 'minute', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (187, 4, 'semana', 'seh-MAH-nah', 'week', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (188, 4, 'mes', 'mehs', 'month', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (189, 4, 'número', 'NOO-meh-roh', 'number', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (190, 4, 'rojo', 'RROH-hoh', 'red', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (191, 4, 'azul', 'ah-THOOL', 'blue', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (192, 4, 'verde', 'BEHR-deh', 'green', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (193, 4, 'blanco', 'BLAHN-koh', 'white', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (194, 4, 'negro', 'NEH-groh', 'black', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (195, 4, 'uno', 'OO-noh', 'one', 'number', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (196, 4, 'dos', 'dohs', 'two', 'number', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (197, 4, 'tres', 'trehs', 'three', 'number', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (198, 4, 'cuatro', 'KWAH-troh', 'four', 'number', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (199, 4, 'cinco', 'THEEN-koh', 'five', 'number', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (200, 4, 'diez', 'dyehth', 'ten', 'number', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (201, 5, 'leche', 'LEH-cheh', 'milk', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (202, 5, 'café', 'kah-FEH', 'coffee', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (203, 5, 'carne', 'KAR-neh', 'meat', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (204, 5, 'fruta', 'FROO-tah', 'fruit', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (205, 5, 'manzana', 'mahn-THAH-nah', 'apple', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (206, 5, 'naranja', 'nah-RAHN-hah', 'orange', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (207, 5, 'huevo', 'WEH-boh', 'egg', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (208, 5, 'queso', 'KEH-soh', 'cheese', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (209, 5, 'azúcar', 'ah-THOO-kar', 'sugar', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (210, 5, 'sal', 'sahl', 'salt', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (211, 5, 'plato', 'PLAH-toh', 'plate', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (212, 5, 'vaso', 'BAH-soh', 'glass', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (213, 5, 'cuchillo', 'koo-CHEE-yoh', 'knife', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (214, 5, 'tenedor', 'teh-neh-DOR', 'fork', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (215, 5, 'cuchara', 'koo-CHAH-rah', 'spoon', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (216, 5, 'botella', 'boh-TEH-yah', 'bottle', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (217, 5, 'papel', 'pah-PEHL', 'paper', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (218, 5, 'carta', 'KAR-tah', 'letter', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (219, 5, 'teléfono', 'teh-LEH-foh-noh', 'telephone', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (220, 5, 'reloj', 'rreh-LOH', 'clock', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (221, 5, 'llave', 'YAH-beh', 'key', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (222, 5, 'bolsa', 'BOHL-sah', 'bag', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (223, 5, 'caja', 'KAH-hah', 'box', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (224, 5, 'regalo', 'rreh-GAH-loh', 'gift', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (225, 5, 'foto', 'FOH-toh', 'photo', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (226, 5, 'película', 'peh-LEE-koo-lah', 'movie', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (227, 5, 'música', 'MOO-see-kah', 'music', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (228, 5, 'canción', 'kahn-THYOHN', 'song', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (229, 5, 'juego', 'HWEH-goh', 'game', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (230, 5, 'fiesta', 'FYEHS-tah', 'party', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (231, 5, 'clase', 'KLAH-seh', 'class', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (232, 5, 'profesor', 'proh-feh-SOR', 'teacher', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (233, 5, 'estudiante', 'ehs-too-DYAHN-teh', 'student', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (234, 5, 'médico', 'MEH-dee-koh', 'doctor', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (235, 5, 'policía', 'poh-lee-THEE-ah', 'police', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (236, 5, 'soldado', 'sohl-DAH-doh', 'soldier', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (237, 5, 'jefe', 'HEH-feh', 'boss', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (238, 5, 'cliente', 'KLYEHN-teh', 'client', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (239, 5, 'jugar', 'hoo-GAR', 'to play', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (240, 5, 'cantar', 'kahn-TAR', 'to sing', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (241, 5, 'bailar', 'bay-LAR', 'to dance', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (242, 5, 'aprender', 'ah-prehn-DEHR', 'to learn', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (243, 5, 'enseñar', 'ehn-seh-NYAR', 'to teach', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (244, 5, 'ayudar', 'ah-yoo-DAR', 'to help', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (245, 5, 'cocinar', 'koh-thee-NAR', 'to cook', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (246, 5, 'lavar', 'lah-BAR', 'to wash', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (247, 5, 'limpiar', 'leem-PYAR', 'to clean', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (248, 5, 'viajar', 'byah-HAR', 'to travel', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (249, 5, 'recordar', 'rreh-kor-DAR', 'to remember', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (250, 5, 'olvidar', 'ohl-bee-DAR', 'to forget', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (251, 6, 'dedo', 'DEH-doh', 'finger', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (252, 6, 'pierna', 'PYEHR-nah', 'leg', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (253, 6, 'rodilla', 'rroh-DEE-yah', 'knee', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (254, 6, 'espalda', 'ehs-PAHL-dah', 'back', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (255, 6, 'pecho', 'PEH-choh', 'chest', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (256, 6, 'cuello', 'KWEH-yoh', 'neck', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (257, 6, 'oreja', 'oh-REH-hah', 'ear', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (258, 6, 'nariz', 'nah-REETH', 'nose', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (259, 6, 'diente', 'DYEHN-teh', 'tooth', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (260, 6, 'lengua', 'LEHN-gwah', 'tongue', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (261, 6, 'pelo', 'PEH-loh', 'hair', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (262, 6, 'piel', 'pyehl', 'skin', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (263, 6, 'sangre', 'SAHN-greh', 'blood', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (264, 6, 'lluvia', 'YOO-byah', 'rain', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (265, 6, 'nieve', 'NYEH-beh', 'snow', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (266, 6, 'viento', 'BYEHN-toh', 'wind', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (267, 6, 'nube', 'NOO-beh', 'cloud', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (268, 6, 'tormenta', 'tor-MEHN-tah', 'storm', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (269, 6, 'estrella', 'ehs-TREH-yah', 'star', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (270, 6, 'piedra', 'PYEH-drah', 'stone', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (271, 6, 'hoja', 'OH-hah', 'leaf', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (272, 6, 'hierba', 'YEHR-bah', 'grass', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (273, 6, 'bosque', 'BOHS-keh', 'forest', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (274, 6, 'jardín', 'har-DEEN', 'garden', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (275, 6, 'verdura', 'behr-DOO-rah', 'vegetable', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (276, 6, 'patata', 'pah-TAH-tah', 'potato', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (277, 6, 'tomate', 'toh-MAH-teh', 'tomato', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (278, 6, 'cebolla', 'theh-BOH-yah', 'onion', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (279, 6, 'arroz', 'ah-RROHTH', 'rice', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (280, 6, 'pescado', 'pehs-KAH-doh', 'fish (food)', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (281, 6, 'pollo', 'POH-yoh', 'chicken', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (282, 6, 'sopa', 'SOH-pah', 'soup', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (283, 6, 'ensalada', 'ehn-sah-LAH-dah', 'salad', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (284, 6, 'postre', 'POHS-treh', 'dessert', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (285, 6, 'desayuno', 'deh-sah-YOO-noh', 'breakfast', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (286, 6, 'almuerzo', 'ahl-MWEHR-thoh', 'lunch', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (287, 6, 'cena', 'THEH-nah', 'dinner', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (288, 6, 'lunes', 'LOO-nehs', 'Monday', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (289, 6, 'martes', 'MAR-tehs', 'Tuesday', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (290, 6, 'miércoles', 'MYEHR-koh-lehs', 'Wednesday', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (291, 6, 'jueves', 'HWEH-behs', 'Thursday', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (292, 6, 'viernes', 'BYEHR-nehs', 'Friday', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (293, 6, 'sábado', 'SAH-bah-doh', 'Saturday', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (294, 6, 'domingo', 'doh-MEEN-goh', 'Sunday', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (295, 6, 'alto', 'AHL-toh', 'tall', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (296, 6, 'bajo', 'BAH-hoh', 'short', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (297, 6, 'largo', 'LAR-goh', 'long', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (298, 6, 'gordo', 'GOR-doh', 'fat', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (299, 6, 'delgado', 'dehl-GAH-doh', 'thin', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (300, 6, 'fuerte', 'FWEHR-teh', 'strong', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (301, 7, 'baño', 'BAH-nyoh', 'bathroom', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (302, 7, 'cocina', 'koh-THEE-nah', 'kitchen', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (303, 7, 'habitación', 'ah-bee-tah-THYOHN', 'room', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (304, 7, 'oficina', 'oh-fee-THEE-nah', 'office', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (305, 7, 'fábrica', 'FAH-bree-kah', 'factory', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (306, 7, 'granja', 'GRAHN-hah', 'farm', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (307, 7, 'isla', 'EES-lah', 'island', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (308, 7, 'lago', 'LAH-goh', 'lake', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (309, 7, 'desierto', 'deh-SYEHR-toh', 'desert', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (310, 7, 'valle', 'BAH-yeh', 'valley', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (311, 7, 'colina', 'koh-LEE-nah', 'hill', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (312, 7, 'cueva', 'KWEH-bah', 'cave', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (313, 7, 'autobús', 'ow-toh-BOOS', 'bus', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (314, 7, 'tren', 'trehn', 'train', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (315, 7, 'avión', 'ah-BYOHN', 'airplane', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (316, 7, 'barco', 'BAR-koh', 'boat', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (317, 7, 'bicicleta', 'bee-thee-KLEH-tah', 'bicycle', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (318, 7, 'camión', 'kah-MYOHN', 'truck', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (319, 7, 'moto', 'MOH-toh', 'motorcycle', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (320, 7, 'metro', 'MEH-troh', 'subway', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (321, 7, 'aeropuerto', 'ah-eh-roh-PWEHR-toh', 'airport', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (322, 7, 'estación', 'ehs-tah-THYOHN', 'station', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (323, 7, 'pantalón', 'pahn-tah-LOHN', 'pants', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (324, 7, 'falda', 'FAHL-dah', 'skirt', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (325, 7, 'vestido', 'behs-TEE-doh', 'dress', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (326, 7, 'abrigo', 'ah-BREE-goh', 'coat', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (327, 7, 'chaqueta', 'chah-KEH-tah', 'jacket', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (328, 7, 'calcetín', 'kahl-theh-TEEN', 'sock', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (329, 7, 'guante', 'GWAHN-teh', 'glove', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (330, 7, 'cinturón', 'theen-too-ROHN', 'belt', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (331, 7, 'bolso', 'BOHL-soh', 'purse', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (332, 7, 'caminar', 'kah-mee-NAR', 'to walk', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (333, 7, 'subir', 'soo-BEER', 'to climb up', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (334, 7, 'bajar', 'bah-HAR', 'to go down', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (335, 7, 'llegar', 'yeh-GAR', 'to arrive', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (336, 7, 'conducir', 'kohn-doo-THEER', 'to drive', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (337, 7, 'volar', 'boh-LAR', 'to fly', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (338, 7, 'nadar', 'nah-DAR', 'to swim', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (339, 7, 'saltar', 'sahl-TAR', 'to jump', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (340, 7, 'caer', 'kah-EHR', 'to fall', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (341, 7, 'levantar', 'leh-bahn-TAR', 'to lift', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (342, 7, 'sentar', 'sehn-TAR', 'to seat', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (343, 7, 'besar', 'beh-SAR', 'to kiss', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (344, 7, 'abrazar', 'ah-brah-THAR', 'to hug', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (345, 7, 'reír', 'rreh-EER', 'to laugh', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (346, 7, 'llorar', 'yoh-RAR', 'to cry', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (347, 7, 'gritar', 'gree-TAR', 'to shout', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (348, 7, 'ganar', 'gah-NAR', 'to win', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (349, 7, 'perder', 'pehr-DEHR', 'to lose', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (350, 7, 'romper', 'rrohm-PEHR', 'to break', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (351, 8, 'primavera', 'pree-mah-BEH-rah', 'spring', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (352, 8, 'verano', 'beh-RAH-noh', 'summer', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (353, 8, 'otoño', 'oh-TOH-nyoh', 'autumn', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (354, 8, 'invierno', 'een-BYEHR-noh', 'winter', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (355, 8, 'frío', 'FREE-oh', 'cold', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (356, 8, 'calor', 'kah-LOR', 'heat', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (357, 8, 'vaca', 'BAH-kah', 'cow', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (358, 8, 'cerdo', 'THEHR-doh', 'pig', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (359, 8, 'oveja', 'oh-BEH-hah', 'sheep', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (360, 8, 'cabra', 'KAH-brah', 'goat', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (361, 8, 'conejo', 'koh-NEH-hoh', 'rabbit', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (362, 8, 'ratón', 'rrah-TOHN', 'mouse', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (363, 8, 'león', 'leh-OHN', 'lion', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (364, 8, 'oso', 'OH-soh', 'bear', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (365, 8, 'lobo', 'LOH-boh', 'wolf', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (366, 8, 'tigre', 'TEE-greh', 'tiger', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (367, 8, 'elefante', 'eh-leh-FAHN-teh', 'elephant', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (368, 8, 'mono', 'MOH-noh', 'monkey', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (369, 8, 'serpiente', 'sehr-PYEHN-teh', 'snake', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (370, 8, 'abeja', 'ah-BEH-hah', 'bee', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (371, 8, 'mariposa', 'mah-ree-POH-sah', 'butterfly', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (372, 8, 'araña', 'ah-RAH-nyah', 'spider', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (373, 8, 'martillo', 'mar-TEE-yoh', 'hammer', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (374, 8, 'clavo', 'KLAH-boh', 'nail', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (375, 8, 'cuerda', 'KWEHR-dah', 'rope', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (376, 8, 'hilo', 'EE-loh', 'thread', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (377, 8, 'aguja', 'ah-GOO-hah', 'needle', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (378, 8, 'tijeras', 'tee-HEH-rahs', 'scissors', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (379, 8, 'escalera', 'ehs-kah-LEH-rah', 'ladder', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (380, 8, 'rueda', 'RRWEH-dah', 'wheel', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (381, 8, 'máquina', 'MAH-kee-nah', 'machine', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (382, 8, 'motor', 'moh-TOR', 'engine', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (383, 8, 'lámpara', 'LAHM-pah-rah', 'lamp', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (384, 8, 'espejo', 'ehs-PEH-hoh', 'mirror', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (385, 8, 'cuadro', 'KWAH-droh', 'picture', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (386, 8, 'alfombra', 'ahl-FOHM-brah', 'carpet', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (387, 8, 'manta', 'MAHN-tah', 'blanket', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (388, 8, 'almohada', 'ahl-moh-AH-dah', 'pillow', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (389, 8, 'toalla', 'toh-AH-yah', 'towel', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (390, 8, 'jabón', 'hah-BOHN', 'soap', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (391, 8, 'cepillo', 'theh-PEE-yoh', 'brush', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (392, 8, 'feliz', 'feh-LEETH', 'happy', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (393, 8, 'triste', 'TREES-teh', 'sad', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (394, 8, 'enfadado', 'ehn-fah-DAH-doh', 'angry', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (395, 8, 'cansado', 'kahn-SAH-doh', 'tired', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (396, 8, 'limpio', 'LEEM-pyoh', 'clean', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (397, 8, 'sucio', 'SOO-thyoh', 'dirty', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (398, 8, 'caliente', 'kah-LYEHN-teh', 'hot', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (399, 8, 'dulce', 'DOOL-theh', 'sweet', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (400, 8, 'amargo', 'ah-MAR-goh', 'bitter', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (401, 9, 'abogado', 'ah-boh-GAH-doh', 'lawyer', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (402, 9, 'ingeniero', 'een-heh-NYEH-roh', 'engineer', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (403, 9, 'enfermero', 'ehn-fehr-MEH-roh', 'nurse', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (404, 9, 'cocinero', 'koh-thee-NEH-roh', 'cook', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (405, 9, 'camarero', 'kah-mah-REH-roh', 'waiter', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (406, 9, 'panadero', 'pah-nah-DEH-roh', 'baker', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (407, 9, 'carpintero', 'kar-peen-TEH-roh', 'carpenter', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (408, 9, 'granjero', 'grahn-HEH-roh', 'farmer', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (409, 9, 'pintor', 'peen-TOR', 'painter', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (410, 9, 'escritor', 'ehs-kree-TOR', 'writer', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (411, 9, 'actor', 'ahk-TOR', 'actor', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (412, 9, 'cantante', 'kahn-TAHN-teh', 'singer', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (413, 9, 'artista', 'ar-TEES-tah', 'artist', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (414, 9, 'dentista', 'dehn-TEES-tah', 'dentist', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (415, 9, 'bombero', 'bohm-BEH-roh', 'firefighter', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (416, 9, 'piloto', 'pee-LOH-toh', 'pilot', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (417, 9, 'guitarra', 'gee-TAH-rrah', 'guitar', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (418, 9, 'piano', 'PYAH-noh', 'piano', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (419, 9, 'tambor', 'tahm-BOR', 'drum', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (420, 9, 'violín', 'byoh-LEEN', 'violin', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (421, 9, 'flauta', 'FLOW-tah', 'flute', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (422, 9, 'baile', 'BAY-leh', 'dance', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (423, 9, 'teatro', 'teh-AH-troh', 'theater', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (424, 9, 'circo', 'THEER-koh', 'circus', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (425, 9, 'fútbol', 'FOOT-bohl', 'soccer', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (426, 9, 'baloncesto', 'bah-lohn-THEHS-toh', 'basketball', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (427, 9, 'tenis', 'TEH-nees', 'tennis', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (428, 9, 'pelota', 'peh-LOH-tah', 'ball', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (429, 9, 'equipo', 'eh-KEE-poh', 'team', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (430, 9, 'partido', 'par-TEE-doh', 'match', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (431, 9, 'premio', 'PREH-myoh', 'prize', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (432, 9, 'juguete', 'hoo-GEH-teh', 'toy', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (433, 9, 'muñeca', 'moo-NYEH-kah', 'doll', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (434, 9, 'medicina', 'meh-dee-THEE-nah', 'medicine', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (435, 9, 'enfermedad', 'ehn-fehr-meh-DAHTH', 'illness', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (436, 9, 'dolor', 'doh-LOR', 'pain', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (437, 9, 'herida', 'eh-REE-dah', 'wound', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (438, 9, 'salud', 'sah-LOOTH', 'health', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (439, 9, 'nacer', 'nah-THEHR', 'to be born', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (440, 9, 'crecer', 'kreh-THEHR', 'to grow', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (441, 9, 'vender', 'behn-DEHR', 'to sell', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (442, 9, 'construir', 'kohns-troo-EER', 'to build', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (443, 9, 'pintar', 'peen-TAR', 'to paint', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (444, 9, 'dibujar', 'dee-boo-HAR', 'to draw', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (445, 9, 'tocar', 'toh-KAR', 'to touch/play', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (446, 9, 'oler', 'oh-LEHR', 'to smell', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (447, 9, 'probar', 'proh-BAR', 'to taste/try', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (448, 9, 'cortar', 'kor-TAR', 'to cut', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (449, 9, 'plantar', 'plahn-TAR', 'to plant', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (450, 9, 'recoger', 'rreh-koh-HEHR', 'to pick up', 'verb', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (451, 10, 'seis', 'says', 'six', 'number', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (452, 10, 'siete', 'SYEH-teh', 'seven', 'number', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (453, 10, 'ocho', 'OH-choh', 'eight', 'number', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (454, 10, 'nueve', 'NWEH-beh', 'nine', 'number', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (455, 10, 'once', 'OHN-theh', 'eleven', 'number', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (456, 10, 'doce', 'DOH-theh', 'twelve', 'number', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (457, 10, 'veinte', 'BAYN-teh', 'twenty', 'number', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (458, 10, 'treinta', 'TRAYN-tah', 'thirty', 'number', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (459, 10, 'cien', 'thyehn', 'hundred', 'number', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (460, 10, 'mil', 'meel', 'thousand', 'number', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (461, 10, 'pueblo', 'PWEH-bloh', 'town', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (462, 10, 'barrio', 'BAH-rryoh', 'neighborhood', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (463, 10, 'mercado', 'mehr-KAH-doh', 'market', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (464, 10, 'museo', 'moo-SEH-oh', 'museum', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (465, 10, 'biblioteca', 'bee-blyoh-TEH-kah', 'library', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (466, 10, 'banco', 'BAHN-koh', 'bank', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (467, 10, 'farmacia', 'far-MAH-thyah', 'pharmacy', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (468, 10, 'panadería', 'pah-nah-deh-REE-ah', 'bakery', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (469, 10, 'restaurante', 'rrehs-tow-RAHN-teh', 'restaurant', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (470, 10, 'castillo', 'kahs-TEE-yoh', 'castle', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (471, 10, 'torre', 'TOH-rreh', 'tower', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (472, 10, 'puerto', 'PWEHR-toh', 'port', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (473, 10, 'bandera', 'bahn-DEH-rah', 'flag', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (474, 10, 'anillo', 'ah-NEE-yoh', 'ring', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (475, 10, 'collar', 'koh-YAR', 'necklace', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (476, 10, 'gafas', 'GAH-fahs', 'glasses', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (477, 10, 'paraguas', 'pah-RAH-gwahs', 'umbrella', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (478, 10, 'maleta', 'mah-LEH-tah', 'suitcase', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (479, 10, 'mochila', 'moh-CHEE-lah', 'backpack', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (480, 10, 'cartera', 'kar-TEH-rah', 'wallet', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (481, 10, 'billete', 'bee-YEH-teh', 'ticket', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (482, 10, 'moneda', 'moh-NEH-dah', 'coin', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (483, 10, 'mapa', 'MAH-pah', 'map', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (484, 10, 'calendario', 'kah-lehn-DAH-ryoh', 'calendar', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (485, 10, 'vela', 'BEH-lah', 'candle', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (486, 10, 'cerilla', 'theh-REE-yah', 'match', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (487, 10, 'pluma', 'PLOO-mah', 'pen/feather', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (488, 10, 'lápiz', 'LAH-peeth', 'pencil', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (489, 10, 'cuaderno', 'kwah-DEHR-noh', 'notebook', 'noun', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (490, 10, 'rico', 'RREE-koh', 'rich', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (491, 10, 'pobre', 'POH-breh', 'poor', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (492, 10, 'joven', 'HOH-behn', 'young', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (493, 10, 'hermoso', 'ehr-MOH-soh', 'beautiful', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (494, 10, 'feo', 'FEH-oh', 'ugly', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (495, 10, 'fácil', 'FAH-theel', 'easy', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (496, 10, 'difícil', 'dee-FEE-theel', 'difficult', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (497, 10, 'rápido', 'RRAH-pee-doh', 'fast', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (498, 10, 'lento', 'LEHN-toh', 'slow', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (499, 10, 'lleno', 'YEH-noh', 'full', 'adjective', NULL);
INSERT INTO words (id, tier, es, pronunciation, en, type, image_url) VALUES (500, 10, 'vacío', 'bah-THEE-oh', 'empty', 'adjective', NULL);